/*
 *
 *  ZDCChatEvent.h
 *  ZDCChat
 *
 *  Created by Zendesk on 30/10/2014.
 *
 *  Copyright (c) 2015 Zendesk. All rights reserved.
 *
 *  By downloading or using the Zopim Chat SDK, You agree to the Zendesk Terms
 *  of Service https://www.zendesk.com/company/terms and Application Developer and API License
 *  Agreement https://www.zendesk.com/company/application-developer-and-api-license-agreement and
 *  acknowledge that such terms govern Your use of and access to the Chat SDK.
 *
 */


#import <Foundation/Foundation.h>


/**
 * Chat log event type.
 */
typedef NS_ENUM(NSUInteger, ZDCChatEventType) {

    /// Unknown event.
    ZDCChatEventTypeUnknown            = 0,

    /// Member (agent) join event.
    ZDCChatEventTypeMemberJoin         = 1,

    /// Member (agent) leave event.
    ZDCChatEventTypeMemberLeave        = 2,

    /// Chat system message event notifying of visitors in the queue.
    ZDCChatEventTypeSystemMessage      = 3,
    
    /// Chat message generated by a trigger event.
    ZDCChatEventTypeTriggerMessage     = 4,
    
    /// Chat message from an agent.
    ZDCChatEventTypeAgentMessage       = 5,
    
    /// Chat message from the visitor.
    ZDCChatEventTypeVisitorMessage     = 6
};


/**
 * Chat event that should be displayed.
 */
@interface ZDCChatEvent : NSObject

/**
 * Unique event Id.
 */
@property (nonatomic, strong) NSString *eventId;

/**
 * Timestamp for the event.
 */
@property (nonatomic, strong) NSNumber *timestamp;

/**
 * Event authors nickname in the system.
 */
@property (nonatomic, strong) NSString *nickname;

/**
 * Event authors display name.
 */
@property (nonatomic, strong) NSString *displayName;

/**
 * Chat message (may be nil depending on the type of event).
 */
@property (nonatomic, strong) NSString *message;

/**
 * Event type.
 */
@property (nonatomic, assign) ZDCChatEventType type;

/**
 * Indicates whether this event has been confirmed by the server or is a local notification.
 */
@property (nonatomic, assign) BOOL verified;

/**
 * Number of visitors in the queue for events of type ZDCChatEventTypeSystemMessage.
 */
@property (nonatomic, strong) NSNumber *visitorQueue;

/**
 * YES if this is the first message by the author.
 */
@property (nonatomic, assign) BOOL firstMessage;

/**
 * YES if this is the first message by the author since another presentable 
 * event occured (avatar should be shown).
 */
@property (nonatomic, assign) BOOL leadMessage;


@end

